blog_api:
    resource: "@BlogAPIBundle/Resources/config/routing.yml"
    prefix:   /tests


acme_blog:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

acme_test:
    resource: "@AcmeTestBundle/Resources/config/routing.yml"
    prefix:   /


contact:
  path: /contact
  defaults: { _controller: AcmeDemoBundle:Main:contact}