parameters:
     blog_base_crud.base_entity_service.class: Blog\BaseCRUDBundle\Service\BaseCRUDService

services:
 blog_base_crud.fake_entity_service:
        class: %blog_base_crud.base_entity_service.class%
        arguments: [@doctrine.orm.entity_manager, @form.factory, 'Blog\BaseCRUDBundle\Tests\Form\FakeEntityType', 'Blog\BaseCRUDBundle\Tests\Entity\FakeEntity']



#services:
#    blog_base_crud.example:
#        class: %blog_base_crud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]