parameters:
     blog_base_crud.base_entity_service.class: Blog\BaseCRUDBundle\Service\BaseCRUDService

services:
    blog_base_crud.fake_entity_service:
          class: %blog_base_crud.base_entity_service.class%
          arguments: [@doctrine.orm.entity_manager, @form.factory, 'Blog\BaseCRUDBundle\Tests\Form\FakeEntityType', 'Blog\BaseCRUDBundle\Tests\Entity\FakeEntity']

    blog_base_crud.fractal_listener:
        class: Blog\BaseCRUDBundle\Listener\FractalListener
        arguments:
          - @fos_rest.view_handler
          - @doctrine.orm.entity_manager
          - "%blog_fractal_transform.fractal_transform.transformer_namespace%"
          - "%blog_fractal_transform.fractal_transform.optional%"
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 255}




#services:
#    blog_base_crud.example:
#        class: %blog_base_crud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]