blog_api_homepage:
    path:     /user/{name}
    defaults: { _controller: BlogAPIBundle:Default:index }


# User Routes
blog_api_homepage:
    pattern:  /user/{uuid}.{_format}
    defaults: { _controller: PulseAPIBundle:Project:get, _format: ~, entityService: pulse_api.project_service}
    requirements:
        _method: GET
        id: "\d+"



blog_api_users_add:
    path:     /user
    defaults: { _controller: BlogAPIBundle:User:add, _format: ~, entityService: blog_api.user_service }
    requirements:
        _method: POST
        id: "\d+"

blog_api_users_list:
    path:     /user
    defaults: { _controller: BlogAPIBundle:User:getUsersInfo, _format: ~ }
    methods: GET

blog_api_users_get:
    path:     /user/{uuid}.{_format}
    defaults: { _controller: BlogAPIBundle:User:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"


blog_api_users_create:
    path:     /user-create.{_format}
    defaults: { _controller: BlogAPIBundle:User:create, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"
