<?php

namespace Blog\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    /**
     * Returns all tasks in BD ordered by name.
     * @return array
     */
    public function findAllTasks()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM BlogTodoBundle:Task p ORDER BY p.NAME  ASC'
            )
            ->getResult();
    }
}
